### ISSUE TITLE
v1 [Tracking]

### ISSUE THREAD

**Issue by insyri** [rsource-open-source/rsource-api#2]
# Process
- [ ] Create SQL structure draft
- [ ] Revise API link structure
- [ ] Initialize project
- [ ] Sanitization
- [ ] Penetration testing
- [ ] Optimization
- [ ] Documentation And Wiki
- [ ] Find host [ Release ]
